### PR TITLE
Multiple reasoners

### PR DESCRIPTION
**Pull request by DanielVoogsgerd**
Moves the main.rs eflint reasoner to a separate binary and splits the implementation side from the policy reasoner binary.

Also adds a no_op reasoner which will always grant requests.

Additionally a posix reasoner is added which looks at the posix file permissions of a file and determines using a map structure if the user has the required permissions.

Feel free to check the current implementation, it will need some TLC.

To do:
- [x] Move eflint reasoner to bin
- [x] Add no_op reasoner
- [x] Add posix reasoner
- [x] Write documentation of project structure.
 
The main rought edge right now is the mapping between uids and the users in Brane. Ideally, we inject some adapter for different mapping backends e.g. File based (yaml) or LDAP/AD.

### CODE REVIEW

**Comment by Lut99** [comment]
When you're done with this PR, would you mind taking the trouble of merging it with [`clippy-fixes`](https://github.com/epi-project/policy-reasoner/tree/clippy-fixes)? :upside_down_face:

I can also just push it to `main`, but I figured it may be easier to tackle the merge separately.

**Comment by DanielVoogsgerd** [comment]
Will do

**Comment by DanielVoogsgerd** [comment]
Okay, we decided to build all checkers as separate images and specify in node.yml which one we will use.

**Comment by DanielVoogsgerd** [comment]
> When you're done with this PR, would you mind taking the trouble of merging it with [`clippy-fixes`](https://github.com/epi-project/policy-reasoner/tree/clippy-fixes)? 🙃
> 
> I can also just push it to `main`, but I figured it may be easier to tackle the merge separately.

Feel free to push the clippy fixes to main (or take the rebased branch on my GH repo). Once that is done we can merge this branch as well (all conflicts have been resolved already)

**Comment by Lut99** [comment]
OK! Thanks! Let's see if I can merge this... hold on...

**Comment by Lut99** [comment]
Oh no, I messed up :joy: I thought I was supposed to merge these myself :#

**Comment by DanielVoogsgerd** [comment]
Haha, no worries, I can probably get them conflict free again

**Comment by Lut99** [comment]
Oh, are you looking into it? I was already trying to merge it myself, but that's maybe easier :)

**Comment by DanielVoogsgerd** [comment]
They are conflict free again, I recommend a rebase merge strategy right now, that should suffice.

**Comment by Lut99** [comment]
:D

**Pull request merged**
