### PR TITLE
chore(deps): Move dependencies to workspace

### PR DESCRIPTION
**Pull request by DanielVoogsgerd**
Also upgraded them to their latest release

@lut99: Please do not merge yet, we first have to upgrade eflint-json to use the latest version of enum-debug as well.

### CODE REVIEW

**Comment by Lut99** [comment]
Alright, `eflint-json` is updated. See the latest commit over at the `incorrect-is-invariant` branch.

**Comment by DanielVoogsgerd** [comment]
> Alright, `eflint-json` is updated. See the latest commit over at the `incorrect-is-invariant` branch.

Lovely, let me check if the lockfile needs updating (I assume so)

**Comment by DanielVoogsgerd** [comment]
Okay, I think we should try to merge it now.

Let me quickly explain what it is we are precisely running into now. Below, our inverted dependency tree (read: the reason stuff is installed).

enum-debug@1.0.0 is installed because the main branch requires it to be installed. I assume by the definition of in the lock file. However, I am actually running this inside policy reasoner. So the problem is that its dependency tree loops back into these packages, which I cannot really control locally, unfortunately.

```
<WORK_DIR>/policy-reasoner $ cargo tree --workspace  -i enum-debug@1.0.0
enum-debug v1.0.0 (https://github.com/Lut99/enum-debug?tag=v1.0.0#cd67d67d)
├── audit-logger v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099)
│   ├── reasonerconn v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099)
│   │   └── srv v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099)
│   │       └── brane-ctl v3.0.0 (https://github.com/epi-project/brane#fb6b0a29)
│   │           └── key-manager v0.1.0 (<WORK_DIR>/policy-reasoner/fix/deny/tools/key-manager)
│   └── srv v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099) (*)
├── deliberation v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099)
│   ├── audit-logger v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099) (*)
│   └── srv v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099) (*)
├── reasonerconn v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099) (*)
└── workflow v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099)
    ├── audit-logger v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099) (*)
    ├── reasonerconn v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099) (*)
    ├── srv v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099) (*)
    └── state-resolver v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099)
        ├── audit-logger v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099) (*)
        ├── reasonerconn v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099) (*)
        └── srv v0.1.0 (https://github.com/epi-project/policy-reasoner#418d4099) (*)
```

**Comment by Lut99** [comment]
Oohhhh right. That's the co-dependency for ya again :sweat:

No worries, I'm working on the PRs to fix that :) with some luck I'll finish it next week somewhere!

**Comment by DanielVoogsgerd** [comment]
I think we should merge, however there is no way of knowing if it works until it has been, unfortunately. If it doesn't, I'll create another PR squashing the next problem.

**Pull request merged**
